#+STARTUP: SHOWEVERYTHING
* Unification Mainnet Helpers

Miscellaneous tools to help support the provisioning and maintenance of Unification Mainnet EVs can be found here. Due to the complexity of the beast, these tools will only work with our standard environments. This library currently only supports Linux. There is some room for differences that the codebase can be modified to handle.

** Revert
This command will wipe all your chain data, use the latest published und versions and genesis. Whilst it may take much time to catch up, this is a good fresh slate if needed.

#+BEGIN_SRC 
python -m undmainchain.upgrade revert
#+END_SRC

** Genesis Export to Amazon S3
The export helper will stop the EV, export the chain data to a JSON file and upload it to Amazon S3, and start the EV again.

#+BEGIN_SRC 
python -m undmainchain.export genesis HEIGHT AWSKEY AWSSECRET
#+END_SRC

** Chain Export to Amazon S3
The entire chain can be compressed and exported to S3. Warning: chains can be large and uploading to S3 can incur cost.

#+BEGIN_SRC 
python -m undmainchain.export chain
#+END_SRC

** Network upgrades
There is also a helper that support network upgrades

#+BEGIN_SRC 
python -m undmainchain.upgrade genesis 700000
#+END_SRC

The helper will wait until the specified block and then perform an upgrade.
